# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: main

jobs:
  build:
#   The type of runner that the job will run on.  
    runs-on: ubuntu-latest

    steps:
    # checks out your repository unde $GITHUB_WORSPACES, so your job can access it
    - name: Step 1 - Checkout main branch from Github
      uses: actions/checkout@v2
      
    - name: Step 2 - Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml

    - name: Step 4 - Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
